sudo: True
language: python
matrix:
  include:
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.3"
    - os: linux
      python: "3.4"
    - os: linux
      python: "3.5"
    - os: linux
      python: "3.6"
    - os: osx
      osx_image: xcode7.3
      language: generic
      env: TOXENV=py36
before_install:
  - if [["$TRAVIS_OS_NAME" == "linux"]]; then $ apt-get update; fi
  - if [["$TRAVIS_OS_NAME" == "linux"]]; then $ apt-get install libunwind8; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
install:
  - pip install codecov
  - pip install tox-travis
script:
  - tox
after_success:
  - codecov --token=d071f49d-847e-4de1-ae11-6a10e8b8aee0
