sudo: True
language: python
matrix:
  include:
    - os: osx
      language: generic
      env: TOXENV=py36
    - os: osx
      language: generic
      env: TOXENV=py27
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.3"
    - os: linux
      python: "3.4"
    - os: linux
      python: "3.5"
    - os: linux
      python: "3.6"
before_install:
  - if [["$TRAVIS_OS_NAME" == "linux"]]; then $ apt-get update; fi
  - if [["$TRAVIS_OS_NAME" == "linux"]]; then $ apt-get install libunwind8; fi
  - if [[ ( "$TRAVIS_OS_NAME" == "osx" ) && ( "$TOXENV" == "py36" ) ]]; then brew update; fi
  - if [[ ( "$TRAVIS_OS_NAME" == "osx" ) && ( "$TOXENV" == "py36" ) ]]; then brew install python3; fi
install:
  - pip install codecov
  - pip install tox-travis
script:
  - tox
after_success:
  - codecov
