sudo: True
language: python
os:
  - linux
env:
  - TOXENV=py27

before_install:
  - if [["$TRAVIS_OS_NAME" == "linux"]]; then $ apt-get update; fi
  - if [["$TRAVIS_OS_NAME" == "linux"]]; then $ apt-get install libunwind8; fi

install:
  - pip install tox

script:
  - tox